"""Central configuration for the parametric Raspberry Pi 5 NAS enclosure.

Coordinate convention used by the assembled model:
    X: left -> right
    Y: front -> rear
    Z: bottom -> top

All values are millimetres unless stated otherwise.  Parameters marked
"MEASURE" are intentionally easy to change after checking real hardware.
"""

# ---------------------------------------------------------------------------
# Hardware envelopes (MEASURE before committing to a full print)
# ---------------------------------------------------------------------------
HDD_L = 194.0
HDD_W = 117.0
HDD_H = 38.0
HDD_CLEARANCE = 1.25
HDD_AIR_GAP = 12.0

PI_CASE_L = 92.0
PI_CASE_W = 66.0
PI_CASE_H = 40.0
PI_CASE_CLEARANCE = 1.5

USB_HUB_L = 110.0
USB_HUB_W = 30.0
USB_HUB_H = 10.0
USB_HUB_CLEARANCE = 1.5
HUB_MOUNT_EDGE = 3.0

FRONT_FAN_SIZE = 120.0
FRONT_FAN_THICKNESS = 25.0
FRONT_FAN_HOLE_SPACING = 105.0
FRONT_FAN_CUTOUT_D = 114.0

REAR_FAN_SIZE = 80.0
REAR_FAN_THICKNESS = 25.0
REAR_FAN_HOLE_SPACING = 71.5
REAR_FAN_CUTOUT_D = 76.0
FAN_MOUNT_HOLE_D = 4.5

# ---------------------------------------------------------------------------
# Print/process assumptions
# ---------------------------------------------------------------------------
WALL = 2.8
FIT_CLEARANCE = 0.30  # per mating side
PRINTER_MODEL = "Bambu Lab P1S"
PRINT_BED_X = 256.0
PRINT_BED_Y = 256.0
PRINT_BED_Z = 256.0
PRINT_USABLE_Z = 250.0
PRINT_BED_EDGE_MARGIN = 3.0  # conservative XY placement margin per edge
NOZZLE_D = 0.4
LAYER_H = 0.20
STL_LINEAR_TOLERANCE = 0.12
STL_ANGULAR_TOLERANCE = 0.15
STL_VERTEX_WELD_TOLERANCE = 1e-5
STL_MIN_TRIANGLE_AREA = 1e-3  # reject slicer-fragile sliver facets
STL_MIN_VOLUME = 1e-3
STL_NORMAL_DOT_MIN = 0.999
COLLISION_VOLUME_EPS = 0.10

# ---------------------------------------------------------------------------
# Overall arrangement
# ---------------------------------------------------------------------------
NAS_EXTERNAL_W = 146.0
NAS_BODY_H = 174.0
FOOT_H = 6.0
FOOT_RADIUS = 8.0
FOOT_INSET = 14.0

FRONT_FAN_TO_HDD = 6.5
CABLE_CHAMBER_DEPTH = 60.0
REAR_FAN_TOP_CLEARANCE = 2.0
REAR_FAN_LEFT_SHIFT = 6.5

HDD_Y = WALL + FRONT_FAN_THICKNESS + FRONT_FAN_TO_HDD
HDD_REAR_Y = HDD_Y + HDD_L
NAS_EXTERNAL_D = HDD_REAR_Y + CABLE_CHAMBER_DEPTH + WALL

HDD_X = (NAS_EXTERNAL_W - HDD_W) / 2.0
HDD_LOWER_Z = 13.0
HDD_UPPER_Z = HDD_LOWER_Z + HDD_H + HDD_AIR_GAP

PI_X = (NAS_EXTERNAL_W - PI_CASE_W) / 2.0
PI_Y = HDD_Y + 10.0
PI_Z = HDD_UPPER_Z + HDD_H + 12.0

FRONT_FAN_X = (NAS_EXTERNAL_W - FRONT_FAN_SIZE) / 2.0
FRONT_FAN_Y = WALL
FRONT_FAN_Z = (NAS_BODY_H - FRONT_FAN_SIZE) / 2.0

REAR_FAN_X = (NAS_EXTERNAL_W - REAR_FAN_SIZE) / 2.0 - REAR_FAN_LEFT_SHIFT
REAR_FAN_Y = NAS_EXTERNAL_D - WALL - REAR_FAN_THICKNESS
REAR_FAN_Z = NAS_BODY_H - WALL - REAR_FAN_SIZE - REAR_FAN_TOP_CLEARANCE

# Hub is rotated: W along X, H along Y, L along Z; ports face rear (+Y).
USB_HUB_X = NAS_EXTERNAL_W - WALL - HUB_MOUNT_EDGE - USB_HUB_CLEARANCE - USB_HUB_W
USB_HUB_Y = HDD_REAR_Y + 20.0
USB_HUB_Z = 48.0

# Structural mid-frame.  The right spine is removable for lateral HDD service.
MID_FRAME_DEPTH = 8.0
MID_FRAME_RING = 8.0
MID_FRAME_CENTER_Y = NAS_EXTERNAL_D / 2.0
MID_FRAME_FRONT_Y = MID_FRAME_CENTER_Y - MID_FRAME_DEPTH / 2.0
MID_FRAME_REAR_Y = MID_FRAME_CENTER_Y + MID_FRAME_DEPTH / 2.0

# Top service lid ends over the mid-frame; the Pi is wholly in front of it.
TOP_SPLIT_Y = MID_FRAME_CENTER_Y
TOP_SERVICE_REAR_Y = MID_FRAME_FRONT_Y
TOP_REAR_FRONT_Y = MID_FRAME_REAR_Y

# ---------------------------------------------------------------------------
# Joint, rail, and local reinforcement geometry
# ---------------------------------------------------------------------------
JOINT_ENGAGEMENT = 4.0
JOINT_THROAT = 8.0
JOINT_HEAD = 12.0
JOINT_EXTRA_DEPTH = 0.4
JOINT_KEY_COUNT = 3


def _joint_fractions(edge_fraction: float) -> tuple[float, ...]:
    """Evenly distribute configured panel keys while retaining edge lands."""
    if JOINT_KEY_COUNT <= 1:
        return (0.5,)
    step = (1.0 - 2.0 * edge_fraction) / (JOINT_KEY_COUNT - 1)
    return tuple(edge_fraction + index * step for index in range(JOINT_KEY_COUNT))


BASE_JOINT_X_FRACTIONS = _joint_fractions(0.22)
TOP_JOINT_X_FRACTIONS = _joint_fractions(0.25)
SIDE_JOINT_Z_FRACTIONS = _joint_fractions(0.24)
CAPTURE_RAIL_H = 4.0
CAPTURE_RAIL_T = 2.4
PANEL_EDGE_TONGUE = 1.4
PANEL_TONGUE_SEGMENT_H = 24.0
PANEL_TONGUE_COUNT = 4
M3_CLEARANCE_D = 3.4

VENT_SLOT_W = 6.0
VENT_SLOT_L = 34.0
VENT_WEB = 5.0
GRILLE_BAR = 4.0
GRILLE_PITCH = 14.0

# HDD skeletal cradle.  End stops sit outside the configured end clearance.
TRAY_THICKNESS = 3.0
TRAY_RAIL_W = 8.0
TRAY_GUIDE_H = 6.0
TRAY_GUIDE_T = 2.4
TRAY_END_STOP_T = 3.0
TRAY_END_CLEARANCE = HDD_CLEARANCE
TRAY_JOIN_LENGTH = 6.0
TRAY_JOIN_THROAT = 4.0
TRAY_JOIN_HEAD = 6.0
HDD_KEEPER_FRACTION = 0.35
HDD_KEEPER_SLOT_L = 12.0
HDD_KEEPER_BYPASS_INSET = 2.4
HDD_KEEPER_BYPASS_END_OVERLAP = 2.0
HDD_KEEPER_BYPASS_W = 2.65
HDD_KEEPER_GUIDE_EMBED = 0.3
HDD_KEEPER_SHOULDER_L = 2.0
HDD_KEEPER_SHOULDER_T = 0.8
HDD_TRAY_SUPPORT_FRONT_Y = 60.0
HDD_TRAY_SUPPORT_REAR_Y = 205.0
HDD_TRAY_SUPPORT_DEPTH = 12.0
HDD_TRAY_SUPPORT_LEDGE_T = 3.0
HDD_TRAY_SUPPORT_OVERLAP = 3.0
HDD_TRAY_LOCATOR_W = 1.6
HDD_TRAY_LOCATOR_L = 6.0
HDD_TRAY_LOCATOR_H = 1.6
HDD_TRAY_LOCATOR_CENTER_INSET = 1.6
HDD_RAIL_FIT_TEST_DEPTH = 32.0
TRAY_OUTER_X = HDD_X - HDD_CLEARANCE - TRAY_GUIDE_T
TRAY_SIDE_EXTENSION = HDD_CLEARANCE + TRAY_GUIDE_T
TRAY_OUTER_W = HDD_W + 2.0 * TRAY_SIDE_EXTENSION
TRAY_TOTAL_L = HDD_L + 2.0 * TRAY_END_CLEARANCE + 2.0 * TRAY_END_STOP_T
TRAY_HALF_L = TRAY_TOTAL_L / 2.0
TRAY_Y = HDD_Y - TRAY_END_CLEARANCE - TRAY_END_STOP_T
HDD_KEEPER_SLOT_Y = HDD_Y + HDD_L * HDD_KEEPER_FRACTION - TRAY_Y

PI_TRAY_W = NAS_EXTERNAL_W - 2.0 * MID_FRAME_RING - 2.0
PI_TRAY_L = PI_CASE_L + 2.0 * PI_CASE_CLEARANCE
PI_TRAY_T = 3.0
PI_TRAY_X = (NAS_EXTERNAL_W - PI_TRAY_W) / 2.0
PI_TRAY_Y = PI_Y - PI_CASE_CLEARANCE
PI_TRAY_Z = PI_Z - PI_TRAY_T
PI_TRAY_FRAME_W = 6.0
PI_TRAY_RAIL_W = 7.0
PI_TRAY_RAIL_END_OVERLAP = 0.5
PI_TRAY_GUIDE_T = 2.4
PI_TRAY_GUIDE_Y = 12.0
PI_TRAY_GUIDE_L = 18.0
PI_TRAY_GUIDE_H = 5.5
PI_TRAY_GUIDE_EMBED = 0.5
PI_TRAY_STRAP_X_OFFSET = 5.0
PI_TRAY_STRAP_SLOT_L = 14.0
PI_TRAY_STRAP_SLOT_W = 3.5
PI_LEDGE_FRONT_Y = PI_Y + 17.0
PI_LEDGE_REAR_Y = PI_Y + PI_CASE_L - 17.0
PI_LEDGE_DEPTH = 14.0
PI_LEDGE_T = 3.0
PI_LEDGE_OVERLAP = 3.0
PI_LOCATOR_W = 1.6
PI_LOCATOR_L = 5.0
PI_LOCATOR_H = 1.6
PI_LOCATOR_CENTER_INSET = 1.6

HUB_MOUNT_BACK_T = 3.0
HUB_MOUNT_LIP = 4.0
HUB_MOUNT_END_LIP_L = 16.0
HUB_MOUNT_SLOT_INSET = 24.0
HUB_MOUNT_CENTER_BRIDGE_W = 4.0
HUB_MOUNT_STRAP_SLOT_L = 10.0
HUB_MOUNT_STRAP_SLOT_W = 1.8
HUB_MOUNT_STRAP_Y_FRACTIONS = (0.34, 0.66)
HUB_MOUNT_W = USB_HUB_H + 2.0 * USB_HUB_CLEARANCE + 2.0 * HUB_MOUNT_EDGE
HUB_MOUNT_L = USB_HUB_L + 2.0 * USB_HUB_CLEARANCE + 2.0 * HUB_MOUNT_EDGE
HUB_MOUNT_BOTTOM_STOP_H = HUB_MOUNT_EDGE + USB_HUB_CLEARANCE
HUB_MOUNT_BOTTOM_STOP_REACH = HUB_MOUNT_LIP + HUB_MOUNT_BACK_T

# Fixed right-side service pedestals. These remain when the removable right
# wall modules leave, supporting both HDD trays at their front/rear ends.
HDD_SERVICE_POST_X = TRAY_OUTER_X + TRAY_OUTER_W + FIT_CLEARANCE
HDD_SERVICE_POST_W = NAS_EXTERNAL_W - WALL - FIT_CLEARANCE - HDD_SERVICE_POST_X
HDD_SERVICE_POST_DEPTH = 6.0
HDD_SERVICE_LEDGE_X = TRAY_OUTER_X + TRAY_OUTER_W - HDD_TRAY_SUPPORT_OVERLAP
HDD_SERVICE_LEDGE_W = NAS_EXTERNAL_W - WALL - FIT_CLEARANCE - HDD_SERVICE_LEDGE_X
HDD_SERVICE_LEDGE_T = 2.4
HDD_SERVICE_FRONT_Y = TRAY_Y + TRAY_END_STOP_T - HDD_SERVICE_POST_DEPTH
HDD_SERVICE_REAR_Y = TRAY_Y + TRAY_TOTAL_L - TRAY_END_STOP_T

FAN_GUARD_DEPTH = 8.0
FAN_GUARD_FRAME = 4.0
REAR_GRILLE_RING_EXTRA = 1.2
REAR_GRILLE_BAR_X_OFFSETS = (-24.0, -8.0, 8.0, 24.0)
FAN_GUARD_CROSSBAR_W = 4.0
FAN_GUARD_CROSSBAR_T = 2.4
CABLE_CLIP_INNER_D = 8.0
CABLE_CLIP_WALL = 2.4
CABLE_CLIP_WIDTH = 10.0
CABLE_CLIP_OPENING = 4.0
CABLE_CLIP_X_LEFT = 20.0
CABLE_CLIP_X_RIGHT = NAS_EXTERNAL_W - CABLE_CLIP_X_LEFT
CABLE_CLIP_Y = HDD_REAR_Y + 34.0

# Cable-tie service slots in the rear chamber floor.
BASE_CABLE_TIE_SLOT_L = 14.0
BASE_CABLE_TIE_SLOT_W = 4.0
BASE_CABLE_TIE_X_INSET = 24.0
BASE_CABLE_TIE_Y_FRACTIONS = (0.58, 0.78)

# Front-edge hand access for the removable Pi service lid.
TOP_FINGER_RELIEF_L = 24.0
TOP_FINGER_RELIEF_W = 8.0
TOP_FINGER_RELIEF_Y = 1.0

# Rear low-voltage service openings (assembly coordinates).
REAR_LOW_SLOT_L = 38.0
REAR_LOW_SLOT_W = 22.0
REAR_LOW_SLOT_X_INSET = 28.0
REAR_LOW_SLOT_Z = WALL + 28.0
REAR_LOW_SLOT_LEFT_X = WALL + REAR_LOW_SLOT_X_INSET
REAR_LOW_SLOT_RIGHT_X = NAS_EXTERNAL_W - WALL - REAR_LOW_SLOT_X_INSET
CABLE_EDGE_CHAMFER = 0.8

# ---------------------------------------------------------------------------
# Provisional connector and bend-zone assumptions (MEASURE)
# ---------------------------------------------------------------------------
HDD_USB_B_X_FROM_LEFT = 35.0
HDD_USB_B_Z_FROM_BOTTOM = 12.0
HDD_USB_B_PLUG_W = 20.0
HDD_USB_B_PLUG_L = 32.0
HDD_USB_B_PLUG_H = 18.0
HDD_USB_B_BEND_W = 26.0
HDD_USB_B_BEND_L = 54.0
HDD_USB_B_BEND_H = 24.0

HDD_DC_X_FROM_LEFT = 82.0
HDD_DC_Z_FROM_BOTTOM = 12.0
HDD_DC_PLUG_D = 12.0
HDD_DC_PLUG_L = 28.0
HDD_DC_BEND_W = 18.0
HDD_DC_BEND_L = 48.0
HDD_DC_BEND_H = 18.0

HDD_SWITCH_X_FROM_LEFT = 104.0
HDD_SWITCH_Z_FROM_BOTTOM = 12.0
HDD_SWITCH_ACCESS_D = 20.0
HDD_SWITCH_ACCESS_L = 20.0

PI_ETHERNET_X_FROM_LEFT = 7.0
PI_ETHERNET_Z_FROM_BOTTOM = 10.0
PI_ETHERNET_PLUG_W = 17.0
PI_ETHERNET_PLUG_L = 30.0
PI_ETHERNET_PLUG_H = 18.0
PI_POWER_X_FROM_LEFT = 48.0
PI_POWER_Z_FROM_BOTTOM = 8.0
PI_POWER_PLUG_W = 12.0
PI_POWER_PLUG_L = 26.0
PI_POWER_PLUG_H = 12.0
PI_USB_X_FROM_LEFT = 28.0
PI_USB_Z_FROM_BOTTOM = 25.0
PI_USB_PLUG_W = 14.0
PI_USB_PLUG_L = 28.0
PI_USB_PLUG_H = 10.0
PI_CABLE_ROUTE_X = 6.5
PI_CABLE_ROUTE_W = 18.0
PI_CABLE_ROUTE_Z = 121.0
PI_CABLE_ROUTE_H = 12.0
PI_ROUTE_BODY_SIDE_INSET = 4.0
PI_ROUTE_BODY_Z_OFFSET = 6.0
PI_ROUTE_INITIAL_L = 48.0
PI_ROUTE_INITIAL_H = 28.0
PI_ROUTE_TURN_OVERLAP = 4.0
PI_ROUTE_FAN_GUARD_GAP = 3.0
REAR_PI_SLOT_H = 34.0
REAR_PI_SLOT_W = PI_CABLE_ROUTE_W + 2.0 * FIT_CLEARANCE
REAR_PI_SLOT_X = PI_CABLE_ROUTE_X + PI_CABLE_ROUTE_W / 2.0
REAR_PI_SLOT_Z = PI_CABLE_ROUTE_Z + PI_CABLE_ROUTE_H / 2.0

USB_PLUG_PROJECTION = 38.0
USB_PLUG_ZONE_MARGIN = 2.0
USB_A_PLUG_W = 14.0
USB_A_PLUG_L = 28.0
USB_A_PLUG_H = 10.0
FAN_USB_ADAPTER_W = 16.0
FAN_USB_ADAPTER_L = 34.0
FAN_USB_ADAPTER_H = 14.0
FAN_USB_ADAPTER_PORT_INDICES = (1, 2)
USB_HUB_PORT_Z_OFFSETS = (16.0, 42.0, 68.0, 94.0)
USB_HUB_REAR_ACCESS_W = 24.0
USB_HUB_REAR_ACCESS_H = 100.0
USB_HUB_REAR_ACCESS_X = USB_HUB_X + USB_HUB_W / 2.0
USB_HUB_REAR_ACCESS_Z = USB_HUB_Z + (
    USB_HUB_PORT_Z_OFFSETS[0] + USB_HUB_PORT_Z_OFFSETS[-1]
) / 2.0
USB_HUB_HOST_BEND_W = 24.0
USB_HUB_HOST_BEND_L = 20.0
USB_HUB_HOST_BEND_H = 18.0

FRONT_FAN_WIRE_X = HDD_X + HDD_W + HDD_CLEARANCE
FRONT_FAN_WIRE_Y = FRONT_FAN_Y + FRONT_FAN_THICKNESS
FRONT_FAN_WIRE_Z = 34.0
FRONT_FAN_WIRE_W = 2.4
FRONT_FAN_WIRE_H = 6.0
REAR_FAN_WIRE_X = 22.0
REAR_FAN_WIRE_Z = REAR_FAN_Z + 12.0
FAN_WIRE_ZONE_W = 6.0
FAN_WIRE_ZONE_H = 6.0

# Routed clearance channels and rear-wall projection (MEASURE cable bundles).
ROUTE_REAR_PROJECTION = 1.0
HDD_LOWER_EXIT_W = 24.0
HDD_LOWER_EXIT_X = REAR_LOW_SLOT_LEFT_X - HDD_LOWER_EXIT_W / 2.0
HDD_LOWER_EXIT_Z = 22.0
HDD_LOWER_EXIT_H = 16.0
HDD_LOWER_FEED_X = 20.0
HDD_LOWER_FEED_Y_OFFSET = 32.0
HDD_LOWER_FEED_Z = 18.0
HDD_LOWER_FEED_W = 45.0
HDD_LOWER_FEED_H = 20.0
HDD_LOWER_CROSS_X = 55.0
HDD_LOWER_CROSS_Y_OFFSET = 22.0
HDD_LOWER_CROSS_Z = 18.0
HDD_LOWER_CROSS_W = 50.0
HDD_LOWER_CROSS_L = 10.0
HDD_LOWER_CROSS_H = 20.0

HDD_UPPER_DROP_X = 72.0
HDD_UPPER_DROP_Y_OFFSET = 38.0
HDD_UPPER_DROP_Z = 32.0
HDD_UPPER_DROP_W = 34.0
HDD_UPPER_DROP_L = 22.0
HDD_UPPER_DROP_H = 56.0
HDD_UPPER_EXIT_W = 28.0
HDD_UPPER_EXIT_X = REAR_LOW_SLOT_RIGHT_X - HDD_UPPER_EXIT_W / 2.0
HDD_UPPER_EXIT_Z = 22.0
HDD_UPPER_EXIT_H = 16.0
HDD_UPPER_USB_BRIDGE_Y_OFFSET = 42.0
HDD_UPPER_USB_BRIDGE_L = 6.0
HDD_UPPER_USB_BRIDGE_Z = 70.0
HDD_UPPER_USB_BRIDGE_H = 10.0

REAR_EXIT_INNER_Y_OFFSET = 18.0
HDD_EXIT_ROUTE_DEPTH = WALL + REAR_EXIT_INNER_Y_OFFSET + ROUTE_REAR_PROJECTION

FAN_ROUTE_ACCESS_GAP = 0.3
FAN_ROUTE_SIDE_W = 2.4
FAN_ROUTE_TOP_H = 6.0
FRONT_FAN_ELBOW_X = USB_HUB_REAR_ACCESS_X - USB_HUB_REAR_ACCESS_W / 2.0 + FAN_ROUTE_ACCESS_GAP
FRONT_FAN_ELBOW_W = FRONT_FAN_WIRE_X + FRONT_FAN_WIRE_W - FRONT_FAN_ELBOW_X
FRONT_FAN_ELBOW_L = USB_HUB_H + 3.0
FRONT_FAN_RISER_X = FRONT_FAN_ELBOW_X
FRONT_FAN_RISER_W = FAN_ROUTE_SIDE_W
FRONT_FAN_RISER_L = 6.0

REAR_FAN_LINK_X = REAR_FAN_X - FAN_WIRE_ZONE_W
REAR_FAN_ROUTE_UNDER_Z = 40.0
REAR_FAN_ROUTE_UNDER_H = 6.0
REAR_FAN_ROUTE_UNDER_X = REAR_FAN_LINK_X
REAR_FAN_ROUTE_UNDER_W = (
    USB_HUB_REAR_ACCESS_X
    + USB_HUB_REAR_ACCESS_W / 2.0
    - FAN_ROUTE_ACCESS_GAP
    - REAR_FAN_ROUTE_UNDER_X
)
REAR_FAN_ROUTE_UNDER_Y = USB_HUB_Y + 0.7
REAR_FAN_ROUTE_UNDER_L = USB_HUB_H - 0.7
REAR_FAN_RISER_X = (
    USB_HUB_REAR_ACCESS_X
    + USB_HUB_REAR_ACCESS_W / 2.0
    - FAN_ROUTE_ACCESS_GAP
    - FAN_ROUTE_SIDE_W
)
REAR_FAN_RISER_W = FAN_ROUTE_SIDE_W
REAR_FAN_RISER_Y = USB_HUB_Y + USB_HUB_H + 0.7
REAR_FAN_RISER_L = 4.0
REAR_FAN_UNDER_LINK_L = REAR_FAN_RISER_Y - (
    REAR_FAN_ROUTE_UNDER_Y + REAR_FAN_ROUTE_UNDER_L
)

HUB_HOST_ROUTE_CROSS_X = 70.0
HUB_HOST_ROUTE_CROSS_Y = HDD_REAR_Y + 5.0
HUB_HOST_ROUTE_CROSS_Z = 45.0
HUB_HOST_ROUTE_CROSS_W = 31.0
HUB_HOST_ROUTE_CROSS_L = 6.0
HUB_HOST_ROUTE_CROSS_H = 6.0
HUB_HOST_ROUTE_RISER_X = 70.0
HUB_HOST_ROUTE_RISER_Y = HDD_REAR_Y + 5.0
HUB_HOST_ROUTE_RISER_Z = 45.0
HUB_HOST_ROUTE_RISER_W = 6.0
HUB_HOST_ROUTE_RISER_L = 6.0
HUB_HOST_ROUTE_RISER_H = PI_CABLE_ROUTE_Z + PI_CABLE_ROUTE_H / 2.0 - HUB_HOST_ROUTE_RISER_Z

# Fit-test matrix
FIT_TEST_CLEARANCES = (0.20, 0.25, 0.30, 0.35, 0.40)
FIT_TEST_RAIL_LENGTH = 30.0
FIT_TEST_DOVETAIL_DEPTH = 3.5
FIT_TEST_DOVETAIL_THROAT = 7.0
FIT_TEST_DOVETAIL_HEAD = 11.0
FIT_TEST_LABEL_PIXEL = 0.70
FIT_TEST_LABEL_GAP = 0.15
FIT_TEST_LABEL_DIGIT_GAP = 0.50
FIT_TEST_LABEL_H = 0.50
FIT_TEST_LABEL_EMBED = 0.10
